name: Rust

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@master
      with:
        envkey_DATABASE_URL: "postgres_url"
        envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        envkey_GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        envkey_ROCKET_DATABASES: ${{ secrets.ROCKET_DATABASES }}
        directory: backend/
    - uses: actions/checkout@v2
    - name: Test if env file exists
      run: ls -la && ls -la backend/
    # selecting a toolchain either by action or manual `rustup` calls should happen
    # before the plugin, as it uses the current rustc version as its cache key
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: backend/
    - name: Build
      run: cargo build --manifest-path backend/Cargo.toml
    - name: Cargo Check
      run: cargo check --manifest-path backend/Cargo.toml
    - name: RustFmt
      run: cargo fmt --manifest-path backend/Cargo.toml
