name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DATABASE_URL: "postgres_url"
        envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        envkey_GOOGLE_CLIENT_URI: ${{ secrets.GOOGLE_CLIENT_URI }}
        envkey_ROCKET_DATABASES: ${{ secrets.ROCKET_DATABASES }}
    - name: Build
      run: cargo build --manifest-path backend/Cargo.toml
    - name: Cargo Check
      run: cargo check --manifest-path backend/Cargo.toml
    - name: RustFmt
      run: cargo fmt --manifest-path backend/Cargo.toml
