name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --manifest-path backend/Cargo.toml
    - name: Cargo Check
      run: cargo check --manifest-path backend/Cargo.toml
    - name: RustFmt
      run: cargo fmt --manifest-path backend/Cargo.toml

